stages:
  - build
  - test
  - release

before_script:
  #- docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.dbogatov.org
  - docker login -u $DOCKER_USER -p $DOCKER_PASS

variables:

  IMAGE: dbogatov/docker-containers

  DOTNETCORE_SDK_TEST: $IMAGE:dotnet-core-$CI_BUILD_REF_NAME
  DOTNETCORE_SDK_RELEASE: $IMAGE:dotnet-core-latest

  JEKYLL_TEST: $IMAGE:jekyll-$CI_BUILD_REF_NAME
  JEKYLL_RELEASE: $IMAGE:jekyll-latest

  MKDOCS_TEST: $IMAGE:mkdocs-$CI_BUILD_REF_NAME
  MKDOCS_RELEASE: $IMAGE:mkdocs-latest

  NGINX_TEST: $IMAGE:nginx-$CI_BUILD_REF_NAME
  NGINX_RELEASE: $IMAGE:nginx-latest

  DEBIAN_TEST: $IMAGE:debian-$CI_BUILD_REF_NAME
  DEBIAN_RELEASE: $IMAGE:debian-latest

### .NET Core SDK

dotnetcore-sdk-build:
  stage: build
  script:
    - docker build --pull -t $DOTNETCORE_SDK_TEST NETCore/SDK
    - docker push $DOTNETCORE_SDK_TEST
  tags:
    - shell

dotnetcore-sdk-test:
  stage: test
  script:
    - docker pull $DOTNETCORE_SDK_TEST
    - docker run -v $CI_PROJECT_DIR/NETCore/SDK/test.sh:/test.sh --entrypoint="/bin/bash" $DOTNETCORE_SDK_TEST /test.sh
  tags:
    - shell

dotnetcore-sdk-release:
  stage: release
  script:
    - docker pull $DOTNETCORE_SDK_TEST
    - docker tag $DOTNETCORE_SDK_TEST $DOTNETCORE_SDK_RELEASE
    - docker push $DOTNETCORE_SDK_RELEASE
  only:
    - master
  tags:
    - shell

### Jekyll

jekyll-build:
  stage: build
  script:
    - docker build --pull -t $JEKYLL_TEST Jekyll
    - docker push $JEKYLL_TEST
  tags:
    - shell

jekyll-test:
  stage: test
  script:
    - docker pull $JEKYLL_TEST
    - docker run -v $CI_PROJECT_DIR/Jekyll/test.sh:/test.sh --entrypoint="/bin/bash" $JEKYLL_TEST /test.sh
  tags:
    - shell

jekyll-release:
  stage: release
  script:
    - docker pull $JEKYLL_TEST
    - docker tag $JEKYLL_TEST $JEKYLL_RELEASE
    - docker push $JEKYLL_RELEASE
  only:
    - master
  tags:
    - shell

### MkDocs

mkdocs-build:
  stage: build
  script:
    - docker build --pull -t $MKDOCS_TEST MkDocs
    - docker push $MKDOCS_TEST
  tags:
    - shell

mkdocs-test:
  stage: test
  script:
    - docker pull $MKDOCS_TEST
    - docker run -v $CI_PROJECT_DIR/MkDocs/test.sh:/test.sh --entrypoint="/bin/bash" $MKDOCS_TEST /test.sh
  tags:
    - shell

mkdocs-release:
  stage: release
  script:
    - docker pull $MKDOCS_TEST
    - docker tag $MKDOCS_TEST $MKDOCS_RELEASE
    - docker push $MKDOCS_RELEASE
  only:
    - master
  tags:
    - shell

### NGINX

nginx-build:
  stage: build
  script:
    - docker build --pull -t $NGINX_TEST NGINX
    - docker push $NGINX_TEST
  tags:
    - shell

nginx-test:
  stage: test
  script:
    - docker pull $NGINX_TEST
    - docker run -v $CI_PROJECT_DIR/NGINX/test.sh:/test.sh --entrypoint="/bin/bash" $NGINX_TEST /test.sh
  tags:
    - shell

nginx-release:
  stage: release
  script:
    - docker pull $NGINX_TEST
    - docker tag $NGINX_TEST $NGINX_RELEASE
    - docker push $NGINX_RELEASE
  only:
    - master
  tags:
    - shell

### Debian

debian-build:
  stage: build
  script:
    - docker build --pull -t $DEBIAN_TEST NGINX
    - docker push $DEBIAN_TEST
  tags:
    - shell

nginx-test:
  stage: test
  script:
    - docker pull $DEBIAN_TEST
    - docker run -v $CI_PROJECT_DIR/NGINX/test.sh:/test.sh --entrypoint="/bin/bash" $DEBIAN_TEST /test.sh
  tags:
    - shell

nginx-release:
  stage: release
  script:
    - docker pull $DEBIAN_TEST
    - docker tag $DEBIAN_TEST $DEBIAN_RELEASE
    - docker push $DEBIAN_RELEASE
  only:
    - master
  tags:
    - shell
